Repository precice/tutorials, pull requests merged in 2020-12, with the labels that each got.

#127 Initialize with V_g.sub(1) as write_object
  CHT/flow-over-plate/buoyantPimpleFoam-fenics/Solid/heat.py
Labels: bug

#123 Add a quickstart rigid flap tutorial
  FSI/rigid_flap/OpenFOAM-RigidBody/Allclean
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/0.orig/U
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/0.orig/p
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/0.orig/pointDisplacement
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/Fluid.foam
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/constant/dynamicMeshDict
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/constant/transportProperties
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/constant/turbulenceProperties
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/system/blockMeshDict
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/system/controlDict
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/system/decomposeParDict
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/system/fvSchemes
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/system/fvSolution
  FSI/rigid_flap/OpenFOAM-RigidBody/Fluid/system/preciceDict
  FSI/rigid_flap/OpenFOAM-RigidBody/README.md
  FSI/rigid_flap/OpenFOAM-RigidBody/Solid/CMakeLists.txt
  FSI/rigid_flap/OpenFOAM-RigidBody/Solid/rigid_body_solver.cpp
  FSI/rigid_flap/OpenFOAM-RigidBody/overview.png
  FSI/rigid_flap/OpenFOAM-RigidBody/plotDisplacement.sh
  FSI/rigid_flap/OpenFOAM-RigidBody/precice-config.xml
  FSI/rigid_flap/OpenFOAM-RigidBody/removeObsoleteFolders.sh
  FSI/rigid_flap/OpenFOAM-RigidBody/runFluid
  FSI/rigid_flap/OpenFOAM-RigidBody/runSolid
Labels: enhancement

#91 Add SU2-FEniCS Perpendicular Flap FSI Tutorial
  FSI/flap_perp_2D/SU2-FEniCS/Allclean
  FSI/flap_perp_2D/SU2-FEniCS/Allrun
  FSI/flap_perp_2D/SU2-FEniCS/Fluid/euler_config_coupled.cfg
  FSI/flap_perp_2D/SU2-FEniCS/Fluid/fluidMesh.su2
  FSI/flap_perp_2D/SU2-FEniCS/Fluid/initial_flow_00000.dat
  FSI/flap_perp_2D/SU2-FEniCS/README.md
  FSI/flap_perp_2D/SU2-FEniCS/Solid/perp-flap.py
  FSI/flap_perp_2D/SU2-FEniCS/Solid/precice-adapter-config-fsi-s.json
  FSI/flap_perp_2D/SU2-FEniCS/plotDisplacement.sh
  FSI/flap_perp_2D/SU2-FEniCS/precice-config.xml
  FSI/flap_perp_2D/SU2-FEniCS/runFluid
  FSI/flap_perp_2D/SU2-FEniCS/runSolid
Labels: enhancement

#120 Modify FEniCS tutorials to enable parallel runs
  CHT/flow-over-plate/buoyantPimpleFoam-fenics/Solid/heat.py
  CHT/flow-over-plate/buoyantPimpleFoam-fenics/precice-config.xml
  FSI/cylinderFlap/OpenFOAM-FEniCS/precice-config.xml
  FSI/flap_perp/OpenFOAM-FEniCS/Solid/perp-flap.py
  FSI/flap_perp/OpenFOAM-FEniCS/precice-config.xml
  HT/partitioned-heat/fenics-fenics/heat.py
  HT/partitioned-heat/fenics-fenics/precice-config.xml
Labels: compatibility

#141 Move 2D FEniCS cases
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/.gitignore
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/0.orig/U
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/0.orig/p
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/0.orig/pointDisplacement
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/0.orig/vorticity
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/0/U
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/0/p
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/0/pointDisplacement
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/0/vorticity
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/Fluid.foam
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/constant/dynamicMeshDict
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/constant/transportProperties
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/constant/turbulenceProperties
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/system/blockMeshDict
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/system/controlDict
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/system/decomposeParDict
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/system/fvSchemes
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/system/fvSolution
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Fluid/system/preciceDict
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Postprocessing/plot_tip.py
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/README.md
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Solid/cyl-flap.py
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/Solid/precice-adapter-config-fsi-s.json
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/precice-config.xml
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/removeObsoleteFolders.sh
  FSI/cylinderFlap_2D/OpenFOAM-FEniCS/runFluid
  FSI/flap_perp_2D/OpenFOAM-FEniCS/.gitignore
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Allclean
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/0.orig/U
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/0.orig/p
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/0.orig/phi
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/0.orig/pointDisplacement
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/Fluid.foam
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/constant/dynamicMeshDict
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/constant/transportProperties
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/constant/turbulenceProperties
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/system/blockMeshDict
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/system/controlDict
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/system/decomposeParDict
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/system/displacementProbe
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/system/fvSchemes
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/system/fvSolution
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/system/preciceDict
  FSI/flap_perp_2D/OpenFOAM-FEniCS/README.md
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Solid/perp-flap.py
  FSI/flap_perp_2D/OpenFOAM-FEniCS/Solid/precice-adapter-config-fsi-s.json
  FSI/flap_perp_2D/OpenFOAM-FEniCS/precice-config.xml
  FSI/flap_perp_2D/OpenFOAM-FEniCS/removeObsoleteFolders.sh
  FSI/flap_perp_2D/OpenFOAM-FEniCS/runFluid
Labels: bug
