Repository precice/tutorials, pull requests merged in 2020-11, with the labels that each got.

#114 Use same method for flux computation like in HT example.
  CHT/flow-over-plate/buoyantPimpleFoam-fenics/Solid/heat.py
Labels: enhancement, maintainability

#113 Rename fenicsadapter to fenicsprecice
  CHT/flow-over-plate/buoyantPimpleFoam-fenics/Solid/heat.py
  FSI/cylinderFlap/OpenFOAM-FEniCS/Solid/cyl-flap.py
  FSI/flap_perp/OpenFOAM-FEniCS/Solid/perp-flap.py
  HT/partitioned-heat/fenics-fenics/heat.py
Labels: compatibility

#118 Fix wrong visualization in nutils cht.py
  CHT/flow-over-plate/buoyantPimpleFoam-nutils/Nutils/cht.py
Labels: bug

#119 Change FEniCS tutorials to handle new initialization signature of FEniCS-Adapter
  CHT/flow-over-plate/buoyantPimpleFoam-fenics/Solid/heat.py
  FSI/cylinderFlap/OpenFOAM-FEniCS/Solid/cyl-flap.py
  FSI/flap_perp/OpenFOAM-FEniCS/Solid/perp-flap.py
  HT/partitioned-heat/fenics-fenics/heat.py
Labels: compatibility
