Repository precice/tutorials, pull requests merged in 2021-04, with the labels that each got.

#153 Add nutils solver for heat conduction problem
  partitioned-heat-conduction/README.md
  partitioned-heat-conduction/clean-tutorial.sh
  partitioned-heat-conduction/fenics/Allclean
  partitioned-heat-conduction/fenics/clean.sh
  partitioned-heat-conduction/fenics/heat.py
  partitioned-heat-conduction/fenics/problem_setup.py
  partitioned-heat-conduction/fenics/run.sh
  partitioned-heat-conduction/nutils/.gitignore
  partitioned-heat-conduction/nutils/clean.sh
  partitioned-heat-conduction/nutils/heat.py
  partitioned-heat-conduction/nutils/run.sh
Labels: enhancement

#145 Restructure quickstart
  quickstart/README.md
  quickstart/clean-tutorials.sh
  quickstart/fluid-openfoam/0/U
  quickstart/fluid-openfoam/0/p
  quickstart/fluid-openfoam/0/pointDisplacement
  quickstart/fluid-openfoam/clean.sh
  quickstart/fluid-openfoam/constant/dynamicMeshDict
  quickstart/fluid-openfoam/constant/transportProperties
  quickstart/fluid-openfoam/constant/turbulenceProperties
  quickstart/fluid-openfoam/run.sh
  quickstart/fluid-openfoam/system/blockMeshDict
  quickstart/fluid-openfoam/system/controlDict
  quickstart/fluid-openfoam/system/decomposeParDict
  quickstart/fluid-openfoam/system/fvSchemes
  quickstart/fluid-openfoam/system/fvSolution
  quickstart/fluid-openfoam/system/preciceDict
  quickstart/images/quickstart-result.png
  quickstart/images/quickstart-setup.png
  quickstart/plotDisplacement.sh
  quickstart/precice-config.xml
  quickstart/solid-cpp/CMakeLists.txt
  quickstart/solid-cpp/clean.sh
  quickstart/solid-cpp/rigid_body_solver.cpp
  quickstart/solid-cpp/run.sh
Labels: compatibility

#200 Check PEP8: Exit 1 on failure
  .github/workflows/check-pep8.yml
  elastic-tube-1d/fluid-python/thetaScheme.py
Labels: bug

#203 Add a check for the image sizes
  .github/workflows/checks.yaml
  tools/check-size.sh
Labels: maintainability

#205 Add a shellcheck action
  .github/workflows/checks.yaml
  flow-over-heated-plate-steady-state/solid-codeaster/run.sh
  quickstart/solid-cpp/clean.sh
Labels: maintainability

#209 Improve elastic-tube-1d code and documentation
  elastic-tube-1d/README.md
  elastic-tube-1d/fluid-cpp/src/FluidSolver.cpp
  elastic-tube-1d/fluid-python/FluidSolver.py
  elastic-tube-1d/fluid-python/run.sh
  elastic-tube-1d/plot-diameter.sh
  elastic-tube-1d/solid-cpp/src/SolidSolver.cpp
  elastic-tube-1d/solid-python/SolidSolver.py
Labels: maintainability
