Repository precice/tutorials, pull requests merged in 2022-02, with the labels that each got.

#234 flow-over-heated-plate: Remove unnecessary parameter
  changelog-entries/234.md
  flow-over-heated-plate-nearest-projection/fluid-openfoam/constant/thermophysicalProperties
  flow-over-heated-plate-steady-state/fluid-openfoam/constant/thermophysicalProperties
  flow-over-heated-plate/fluid-openfoam/constant/thermophysicalProperties
Labels: enhancement, maintainability

#232 elastic-tube-1d: Remove unnecessary read statement
  changelog-entries/232.md
  elastic-tube-1d/fluid-cpp/src/FluidSolver.cpp
Labels: bug

#256 Making output directories for all FEniCS participants consistent
  flow-over-heated-plate/solid-fenics/solid.py
  partitioned-heat-conduction-complex/fenics/heat.py
  partitioned-heat-conduction/fenics/heat.py
  perpendicular-flap/solid-fenics/solid.py
  tools/cleaning-tools.sh
  volume-coupled-diffusion/fenics/volume-coupled-diffusion.py
Labels: compatibility

#222 Add FEniCS as a solid participant for elastic-tube-3d
  elastic-tube-3d/README.md
  elastic-tube-3d/images/tutorials-elastic-tube-3d-plot.png
  elastic-tube-3d/plot-all-displacements.sh
  elastic-tube-3d/precice-config.xml
  elastic-tube-3d/solid-fenics/clean.sh
  elastic-tube-3d/solid-fenics/precice-adapter-config-fsi-s.json
  elastic-tube-3d/solid-fenics/run.sh
  elastic-tube-3d/solid-fenics/solid.py
Labels: enhancement
