Repository precice/tutorials, pull requests merged in 2024-11, with the labels that each got.

#590 Relax FEniCS requirements.
  changelog-entries/590.md
  channel-transport-reaction/chemical-fenics/requirements.txt
  channel-transport-reaction/fluid-fenics/requirements.txt
  elastic-tube-3d/solid-fenics/requirements.txt
  flow-over-heated-plate/solid-fenics/requirements.txt
  partitioned-heat-conduction-complex/solver-fenics/requirements.txt
  partitioned-heat-conduction-overlap/solver-fenics/requirements.txt
  partitioned-heat-conduction/solver-fenics/requirements.txt
  perpendicular-flap/solid-fenics/requirements.txt
  volume-coupled-diffusion/solver-fenics/requirements.txt
Labels: compatibility

#587 System tests: Enable preCICE debug messages and symbols via an argument
  changelog-entries/587.md
  tools/tests/README.md
  tools/tests/components.yaml
  tools/tests/docker-compose.template.yaml
  tools/tests/dockerfiles/ubuntu_2204/Dockerfile
  tools/tests/reference_versions.yaml
Labels: systemtests

#595 System tests: Run all elastic-tube-1d tests in release_test
  tools/tests/tests.yaml
Labels: systemtests

#597 `oscillator-overlap`: Make consistent with `oscillator`
  changelog-entries/597.md
  oscillator-overlap/precice-config.xml
  oscillator-overlap/solver-python/oscillator.py
  oscillator-overlap/solver-python/problemDefinition.py
  oscillator-overlap/solver-python/timeSteppers.py
Labels: enhancement, maintainability

#598 Simplify code of oscillator
  oscillator-overlap/solver-python/oscillator.py
  oscillator/solver-python/oscillator.py
Labels: maintainability
